name: FloatingText
author: [ElectroGames, skyss0fly]
version: 1.1.0
api: 5.0.0
main: skyss0fly\FloatingText\Main
description: Add FloatingTexts to your server

permissions:
  ft.command:
  default: op
  ft.command.admin:
    default: op
